name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-lint-test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.10

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run Tests
        run: make test
